FROM debian:10

RUN apt-get update && apt-get install -y \
    nginx \
    openssl

COPY ./conf/nginx.conf /etc/nginx/sites-available/default

RUN openssl req \
    -newkey rsa:4096 -x509 -days 365 -sha256 -nodes \
	-keyout /etc/ssl/private/nginx.key \
	-out /etc/ssl/certs/nginx.crt -sha256 \
    -subj "/C=DE/ST=Baden-Württemberg/L=Heilbronn/O=Frmessin Inc./OU=IT Department/CN=frmessin.42.fr"

# EXPOSE 443

CMD [ "nginx", "-g", "daemon off;" ]